# Generated by Django 3.0.6 on 2020-05-23 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='score',
            new_name='max_score',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answers', to='learn.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'is_correct')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='answer',
            order_with_respect_to='question',
        ),
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to='test',
        ),
        migrations.AlterOrderWithRespectTo(
            name='test',
            order_with_respect_to='subject',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_d',
        ),
    ]
